### PR TITLE
Added Footer design

### PR DESCRIPTION
**Pull request by CrisH2307**
Refactored code design (From 146 to 58 lines of code) and added footer gradient color. Solved on #14 

Screenshot 2024-12-24 at 11 25 10 PM

### CODE REVIEW

**Comment by KaosElegent** [comment]
Not sure if I'm a big fan of the gradient honestly 😅

**Comment by KaosElegent** [comment]
Do u have any opinions about the gradient? Do u think it's necessary? @CrisH2307

**Comment by CrisH2307** [comment]
> Do u have any opinions about the gradient? Do u think it's necessary? @CrisH2307

I was about to change gradient black to red (from left to right). `from... to...` and get rid of `via`

**Comment by KaosElegent** [comment]
> > Do u have any opinions about the gradient? Do u think it's necessary? @CrisH2307
> 
> I was about to change gradient black to red (from left to right). `from... to...` and get rid of `via`

hmm, the only issue I had with a gradient is that since the rest of the website didn't have a gradient, this came off too strong. It diverts the user's attention to the footer, whereas I think the footer should exist without standing out too much. Obviously, I'm not against a gradient, as long as it doesn't seem out of place

**Comment by CrisH2307** [comment]
> > > Do u have any opinions about the gradient? Do u think it's necessary? @CrisH2307
> > 
> > 
> > I was about to change gradient black to red (from left to right). `from... to...` and get rid of `via`
> 
> hmm, the only issue I had with a gradient is that since the rest of the website didn't have a gradient, this came off too strong. It diverts the user's attention to the footer, whereas I think the footer should exist without standing out too much. Obviously, I'm not against a gradient, as long as it doesn't seem out of place

Commited at [1053867]. 
Screenshot 2024-12-30 at 9 56 37 PM

**Review by KaosElegent — APPROVED** [review]

**Pull request merged**
